### ISSUE TITLE
Do it is running in somewhere?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#15]

**Comment by TheFive** [comment]
Yep, i have a small development instance running on thefive.sabic.uberspace.de/osmbc.html
(Parallel to OSMCount which runs on thefive.sabic.uberspace.de/index.html).

Can you send my your osm account (may be per PN via https://www.openstreetmap.org/user/TheFive), so that i can enable you for the software. It is using oauth on OSM Logon.

**Comment by TheFive** [comment]
Hi, you should now have full access to OSMBC.

I did not test UserAccounts with a space in it, do not know wether passport the node.js oauth module or the session store has a problem with it or not. But i think, it will work.


Christoph

**Comment by alexandre-mbm** [comment]
It works. I will analyze it and look if I can help you with something.
