### ISSUE TITLE
Spelling mistake at http://thefive.sabic.uberspace.de/article/create

### ISSUE THREAD

**Issue by SomeoneElseOSM** [TheFive/osmbc#150]
"Please check your link for dublicates before collecting." should be "Please check your link for duplicates before collecting.".

Also it's not clear what you're supposed to check for duplicates against - the screen below the add box is empty.

**Comment by TheFive** [comment]
If you search for e.g. a https:// .. string the following happens:
![image](https://cloud.githubusercontent.com/assets/6240370/11085225/1f37314c-8844-11e5-8251-86889cb2b83f.png)

If the link is not found the screen is:
![image](https://cloud.githubusercontent.com/assets/6240370/11085240/3d9687e6-8844-11e5-9c03-7eb9ea5782e9.png)


Hope this helps. Otherwise please specify which add box you are talking about.
