### ISSUE TITLE
Possibility to have the comments per language?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#165]

**Comment by alexandre-mbm** [comment]
+1 :+1: 

I like of this hint. I also like the idea of OSMBC having a full comments area. However, I am in favor that the developer attack first issues regarding bugs and views.

**I desire that this issue be accept, not closed.** And that it be added to the developer's reflections regarding a full comments area (another issue).

**Comment by TheFive** [comment]
@fredao (1) I do not like to be talked about as "The Developer". Can you tell that Alexandre please.

@fredao:  (2) I am thinking about changing the comments area to a one field per comment one (so that the comment field has a relation to the author, like a forum). If i change the data model for a language specific communication, how can we assure, that a communication between the languages can be done ?

**Comment by alexandre-mbm** [comment]
@fredao, I will talk @TheFive at Slack.

**Comment by TheFive** [comment]
We have discussed that at the fossgis hacking event in Essen. Common sense was to have one comment field, that can be used mainly for english comments. Of course, it can be used for language specific things. 
If the amount of comments will be to much, it can be rethought.

**Comment by alexandre-mbm** [comment]
Mentions to teams would be interesting: `@EN`, `@ES`, `@PT`...
