### ISSUE TITLE
Replace in Markdown the sequnce "] (" with "](" 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#197]

**Comment by alexandre-mbm** [comment]
Why this is happening? Is it only human carelessness? Or a tool issue?

**Comment by fredao** [comment]
It happens during translation in Gtranslate.

**Comment by alexandre-mbm** [comment]
I would prefer a markdown validation, including this and others issues. On error, the border of the text area would be red.

**Comment by TheFive** [comment]
The problem is, that every character sequence is valid markdown. On top the markdown in OSMBC is evolving, since 0.4 there is an extended language.
OSMBC Offers a preview to compare, that what the auditor wants to see, with that what the markdown is generating. I think thats exactly whats needed here.

**Comment by alexandre-mbm** [comment]
@TheFive, you could show message for some cases, even with valid markdown. How happens with links that have long expressions (showing red warnings).
