### ISSUE TITLE
separate the two buttons - REVIEW and DID EXPORT - please

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#375]
![image](https://cloud.githubusercontent.com/assets/1868849/13671846/92e242b6-e6d2-11e5-9d1b-28abf9afbc3d.png)

it happens nearly every week that we must reopen a blog, because somebody pressed the EXPORT button unwillingly.

**Comment by lbarrosop** [comment]
+1

**Comment by TheFive** [comment]
Hi fredao:
that are two separat buttons, where should i put the DidExport button to avoid this mistake ?
Or should i color it in another way, please see the standard Bootstrap Buttons here:
http://www.w3schools.com/bootstrap/bootstrap_ref_css_buttons.asp

So ReviewES as Primary Type and Did Export (ES) as Warning ?

**Comment by lbarrosop** [comment]
@TheFive  hi, we run into this problem today when a reviewer make the mistake...I think if you separate the buttons will be ok...an space between them should fix the problem, also your recommendation about the Did Export (ES) as a warning button could be really helpfull since it will be colored as yellow...don't you agree @fredao ?

**Comment by fredao** [comment]
A first step could be "Warning".
And if possible put it at the bottom.

**Comment by fredao** [comment]
But.. we could try Laura's proposal as well. ;-)

**Comment by TheFive** [comment]
Thanks for the hint, i think the user interface is much better understandable, after sorting reviews to reviews.
Only that a lot of space is used for the review information.
