### ISSUE TITLE
take the blog changes "WN294(XX) is exported to WordPress" and "WN294(XX) has been closed"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#384]
out of the mail messages.

This information is not valid for editors anymore, 
* WN294(XX) is exported to WordPress - has no value, because the proofreading is done in OSMBC
* WN294(XX) has been closed -  has no value neither.

the same for 
* WN295 was created - this message doesn't generate any action

**Comment by TheFive** [comment]
before we now start to exclude anything partially, and someone likes to have the information as mail. 
What you want is a mail mode that only sends out review messages ? (only the first or all ?).
I would like to add a flag in this way:

**Comment by fredao** [comment]
it is the blog information to the slack channels.
Important are: 
1. SET to Edit        ->
2. SET to Review  ->
What somebody like to read indiviually I have really no clue.

I fear that to much information are seen more or less as "spam" and the important information are not read.

**Comment by TheFive** [comment]
a) set to Edit and Blog Created should be in sync and just two messages at the same time.
and as it is still possible to create a blog manually (e.g. if you would like to do a chrismas edition...) this is a "social control" of this OSMBC feature.
b) send to wordpress is relevant, because after that changes can only be done in WP.
c) closed is relevant as closed is (for me) equal to published.

(But i am not an active editor for the time).

But if there are more editors sharing your opinion i can reduce the number of status messages in slack.

**Comment by fredao** [comment]
please close the issue
