### ISSUE TITLE
adding existing links to collection

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#404]
when adding an (in another article) already existing link to a collection, there should appear a warning (possible doubles)

**Comment by TheFive** [comment]
mm, all links that are double are shown in that article. Problem: clicking on OK leads to the blog and leaves the article (wished by "The Editors"), so the information is going to be lost.
Next Problem: There are many users, that has switched of the possibility to open an alert when leaving a page, otherwise i can't explain, why there are so many "locked" articles.

**Comment by TheFive** [comment]
This should be solved when saving an article in the new editor. On top in #662 i have implemented an higher visibility to doublette links unter the collection field. For now, this is only updated while SAVE an article. I havn't implemented any live conversation between server and client outside the save buttons yet.
