### ISSUE TITLE
Send marketing out of OSMBC for WeekylOSM

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#440]
The English and Spanish team collect every week (by hand) the so called: highlights. ;-)

Example: 301 ES
Artículos más destacados esta semana:
1.Actualización sobre terremoto en Ecuador.
2.Coming Home: un concierto benéfico para apoyar el alivio del terremoto
Ecuador/Japón. Las ganancias de este concierto serán donadas al equipo de
OpenStreetMap humanitario. Fecha: 1ro de mayo Hora: 15:00-17:00,
3.Usted puede aplicar a una beca para unirse a la SotM 2016 en Bruselas.
4.OSMF busca un “asistente administrativo” a tiempo parcial. Él o ella
será el primer empleado de OSMF, un hecho que no gusta a algunos miembros.
La oferta de trabajo dió como resultado una discusión en la lista de
correo OSMF-Talk sobre la falta de transparencia de la junta OSMF (que fue
un tema importante durante las elecciones de la junta OSMF 2014 y 2015).

und 
Example: 299 EN
_Among others:_
- Like indoor mapping? iD-indoor, a fork of iD editor which aims in addressing this need.
- Have you come across a vandal on OSM? Read more about possibilities for tracking them.
- Heard about Geopedia.info? It displays georeferenced Wikipedia articles on an OpenStreetMap layer.
- Pete Masters of Médecins Sans Frontières‎ France explains the practical benefits of humanitarian mapping.
- Diana S. Sinton describes in Direction Magazine the overall development and the global movement of OpenStreetMap

**Comment by TheFive** [comment]
I try to extract an technique to develop this feature.

A) Generating the text
a1) The extract is the same text as the generated Blog, without categories ?
a2) The extract is a reference to the text, but written in another way.
Of course in a2) OSMBC can offer another text field to fill in, but the work has to be done by the editors

B) Selecting the Articles
Is the selection language dependent ? I assume it should be, as there are may be top interesting articles that are "no translation" to all other languages.

In this case i suggest to introduce a tagging for articles (i have thought of it, just to give you the possibility of developing additional processes, that are not seen now).
To make it simple i would like to add a :star: to the overview list, that is "clickable" so that you can easily set your favorite tag.

There are two tag possibility: 
A) voting tags, that counts the number of users that thats the tag. Can help to create the top list in a distributed manner
B) simple tags, that can be set or unset by every one "last one wins".

of course, that tags itself should be displayable in the overview too.

**Comment by fredao** [comment]
A) Generating the text
Q: a1) The extract is the same text as the generated Blog, without categories ?
A: YES - and without links

B) Selecting the Articles
Q: Is the selection language dependent ? 
A: Yes, because the differnt languages have mostly a differnt view about the important issues

Proposal:
P: To make it simple i would like to add a :star: to the overview list, that is "clickable" so that you can easily set your favorite tag.
A: yes, great ... keep it simple! ;-)

**Comment by TheFive** [comment]
related to #343.

**Comment by TheFive** [comment]
See #453 and #452

**Comment by TheFive** [comment]
See 
https://github.com/TheFive/osmbc/issues/343 for close reason.
