### ISSUE TITLE
inverse  automatic translation from right to left

### ISSUE THREAD

**Issue by lbarrosop** [TheFive/osmbc#480]
translate from left to right works until I have to set ES ready to review because the tool assume that EN is my main language so I can not put ES to review, can we put it reverse???

**Comment by fredao** [comment]
That one should be discussed, because I am really happy with from left to right. That is the normal way of reading. After translation one can switch the language. That is really for a short time. Translation time is much mir time consuming as set a version on review.

**Comment by lbarrosop** [comment]
you got a point, but in that case the tool should let me put somehow ES ready to review, otherwise I will have to change two times my main language and my translation language. The first time for the translation and second for the review status.

**Comment by fredao** [comment]
Exactly - so do I! I accept a  two time language switch because we read from left to right. If you switch the translations process, your eye movment during transaltion process will be multiplied by a factor X, what is time consuming and it slows down your result. So that is not a personal preference, it is a question of ergonomics.

**Comment by lbarrosop** [comment]
sattle then, :+1:

**Comment by lbarrosop** [comment]
or not...we have to wait for the programmer hahahaha

**Comment by TheFive** [comment]
A very quick and dirty solution by code replication... Article Editor is ready for a redesign... using jquery + angular.js.
