### ISSUE TITLE
put a small frame around the flags

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#52]
The Japanese flag is just a red circle for now.

**Comment by Nakaner** [comment]
Well Japan has a white flag with a large red dot. That's why do not see it well on white backgrounds. ;-)

We can add a small black border but the border has to be such thick that it is visible (our flags are tiny). I'll try how a "protected Japan" :-) looks.

**Comment by Nakaner** [comment]
This is the 18 x 12 pixel large Japanese flag with an aritifical 0.2 px thick boundary line. ![(Japanese)](http://blog.openstreetmap.de/wp-uploads//2015/10/jp.svg)

You can use the URL of the flag used here (it is already uploaded to `blog.openstreetmap.de`) if you like it. Older postings will still have the old flag because it is impossible to edit an image via web interface. This has to be done via SSH/FTP.

**Comment by Nakaner** [comment]
Well, Github modifies everything. The right URL is `http://blog.openstreetmap.de/wp-uploads//2015/10/jp.svg`
