### ISSUE TITLE
Automatic translation of Weekly OSM

### ISSUE THREAD

**Issue by MohametLamineNdiaye** [TheFive/osmbc#610]
Good morning,
I introduce myself, my name is Mohamet Lamine Ndiaye and I am a founding member of the OSM / Senegal community, also a founding member of a collective grouping Francophone contributors from the 9 countries of West Africa around the Space project Openstreetmap Francophone and French translator of WeeklyOSM since November 2016.
For the past three weeks, WeeklyOSM's team of French translators has been discussing how to harmonize their work to save time and a methodology that will be used by everyone, especially with regard to the automatic translation of non-French-language links.
What drives me today to make this proposal:
Could not we have another category for the links of all the articles?
Therefore automatic translation will only interest this category.
What do you think? And also if there are other proposals we are listening.
Thank you

**Comment by fredao** [comment]
to specify the idea a bit more ... 
as Mohamet told me - there are a lot of people in Afrique francophone who don't speak English at all. So if we link to English-spoken content each of the link must be added with an automatic translations. This impedes the read flow - if it must be done for *each* link,

Therefore the idea to create a new category "Translated Links" or what ever at the end of each weekly. ... and that is a dream of both of us ... a table filled directly by OSMBC ... and maybe in a table as follows ...
![grafik](https://cloud.githubusercontent.com/assets/1868849/22056969/03057d06-dd63-11e6-9234-20a029eb4496.png)

Maybe it will be used by the French community only, maybe it can help other languages as well.

**Comment by MohametLamineNdiaye** [comment]
Thanks to you Manfred for this contribution.
This is exactly what we need a table that retrieves the links and translates what are not French and so the reading flow will not be spoiled by automatic translations all the time.
It is my wish to have such a painting if not for our friends of west africa I would be obliged to do automatic translation.

**Comment by MohametLamineNdiaye** [comment]
Thanks to you Manfred for this contribution.
This is exactly what we need a table that retrieves the links and translates what are not French and so the reading flow will not be spoiled by automatic translations all the time.
It is my wish to have such a painting if not for our friends of west africa I would be obliged to do automatic translation.

**Comment by TheFive** [comment]
Hi Lamine,
Thanks to both for contribution. 
First, i would assume, that people, that are now aware with english language and working with OpenStreetMap will use the browser included translation feature.
(https://support.google.com/chrome/answer/173424?co=GENIE.Platform%3DDesktop&hl=en)
Many good article in OSM "Bubble" are in english, so it is important for non english speaking mappers, to have an easy access to this information source.
And i can imagine, that it is much easier in clicking on a original language link, getting support by the browser in translating the page, instead of scrolling to the end of the blog, searching for the article of interest and clicking on the translation.
But if there is a need for such a service, AND we are able to manage the additional service, we can introduce the additional category, so that we to that service manually first, so that we get feedback from the community, in which way it is the best to present this additional information.
Do you have a suggestion for a category name, and is it OK to do that manually first. (may be as a test for discussion in one issue ?)
Christoph

**Comment by TheFive** [comment]
I close this issue. Feel free to add a new one, if there is experience with the additional category.
