### ISSUE TITLE
Link on "This weeklyOSM was produced by" broken

### ISSUE THREAD

**Issue by Spec80** [TheFive/osmbc#665]
The link on "produced" on "This weeklyOSM was produced by" at the bottom of every post is pointing to **http://www.weeklyosm.eu/page//"https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages\"**

Link on OSMBC EN export:  ` <a href="\&quot;https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages\&quot;"> produced</a>`

Link on PT export: `<a href=\"https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages"> produzido</a>`

**Comment by TheFive** [comment]
Hi,

how do you generate the export ?
```
<p align="right"><i>This weeklyOSM was <a href=\"https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages\"> produced</a> by Anne Ghisla, Peda, Polyglot, Rogehm, SK53, derFred, jcoupey, jinalfoflia, keithonearth, kreuzschnabel, wambacher.</i></p>

```
Did you inspect the downloaded file with a text editor.

This is my download code:
```
 res.setHeader("Content-disposition", "attachment; filename=" + blog.name + "(" + lang + ")" + moment().locale(config.moment_locale(lang)).format() + ".html");
          res.setHeader("Content-type", "text/html");
          res.end(result.converter, "UTF8");
```
I just set the content-type to text/html, define a filename and a encoding. Its total unclear, why there is a difference in the PT and EN version.

**Comment by Spec80** [comment]
I generated the PT one... clicked the "Download" button with the export tab selected on OSMBC. Opened file on Kate and copy&paste into WP.

EN wasn't me... just copied what was on WP...

Link on both langs (thinks all of them) are broken.

**Comment by TheFive** [comment]
mm, it looks like, that OSMBC is generating what is configured in https://thefive.info/config/editorstrings.

So may be this configuration is wrong.  (i do not know where the &quot in your sample comes from, but i think it is added by an editor, which converts the text to the html escape sequences.

The problem is, that WP adds the link to the www.weeklyosm.eu baselink as a subpage. What does WP need to reference in a working way to the wiki. In a second step this can be changed in the editorstrings section.

I just mention @fredao, may be he is more confirmed with the WP configuration.

**Comment by Spec80** [comment]
Sorry! &quot were a copy&paste error from WP to here!

From OSMBC export (last line):
- EN: `<p align="right"><i>This weeklyOSM was <a href=\"https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages\"> produced</a>` 
- PT: `<p align="right"><i>Este semanárioOSM foi <a href=\"https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages"> produzido</a>`

The href attribute has the " escaped... On EN both and PT just the first.

Export's 1st line:
- EN: `<p>30/05/2017-05/06/2017</p>`
- PT: `<p>30/05/2017-05/06/2017</p>`

WP 1st line:
- EN: `30/05/2017-05/06/2017`
- PT: `<p>30/05/2017-05/06/2017</p>`

The publishing method on EN is making changes to the export... the `<p>` tag getting stripped for example.

**Comment by TheFive** [comment]
I assume, you can copy the downloaded file opened by a texteditor, and you can open the downloaded file with a brower, and copy the contend. I assume, this can make a difference.

But for the broken links the problem is, that WP is adding the href link to its base link, so that as a result
```
http://www.weeklyosm.eu/LINKFROMOSMBC 
```
I have removed the escaping ```\``` from the configuration, hope this will fix the issue next time.

**Comment by TheFive** [comment]
Tested the new export, it now seems to work.

**Comment by Spec80** [comment]
Tested the link on my side! Solved!

BTW, I do know the base link was getting added by the browser ;) Not even WP!!
