### ISSUE TITLE
Ignore commas inside wiki links

### ISSUE THREAD

**Issue by kocio-pl** [TheFive/osmbc#698]
Currently comma inside the wikilink is treated as any other comma and it breaks some calendar entries, for example:

Where | What | When | Country
Colorado | Boulder]] | State of the Map U.S. 2017, [[Boulder | 2017-10-19-2017-10-22

https://osmbc.openstreetmap.de/calendar/preview

**Comment by TheFive** [comment]
The problem is, if you reference
```
[[Boulder, Colorado|Boulder]]
```

I haven't had that syntax in mind while parsing. I will fix it.

As a quickfix i have changed the wiki, and now it is working.

```
[[Boulder%2C_Colorado|Boulder]]
```

**Comment by TheFive** [comment]
P.S. @kocio-pl Thanks for remarking here, i havn't recognized that.

**Comment by TheFive** [comment]
Looks like the Dark Knight has come and did not accept the change. Sorry for that, I have tried to send him an email, as i do not like to start an edit war.
Christoph

**Comment by TheFive** [comment]
The discussion with Verdi P can be seen here.
https://wiki.openstreetmap.org/wiki/User_talk:Verdy_p#Wiki_Calendar_Change_from_21.10.2017

**Comment by kocio-pl** [comment]
Thanks for quick response! This bug is visible, but not critical, and people are using this form for different places (see also Rome and San Juan on preview), so fixing the code would be preferable anyway.

**Comment by TheFive** [comment]
I have decided to reduce the amount of software i have to maintain and will stop the OSMBC Calendar Service (public review and conversion for weeklyOSM). I hope the team will find someone, to do the conversion automated (manual it is a lot of - better: to much - work) in the next two month.

The wiki calendar is now supporting hCalendar microformats, so an automated parser should be much simpler to create than mine was.

**Comment by fredao** [comment]
always trouble with @verdy-p. :( - I think we should stop the calendar immediately. We with this self-proclaimed expert who is constantly screwing around with the wiki syntax without discussing it beforehand. @TheFive I understand your reaction!

**Comment by verdy-p** [comment]
Whjich problem ? The fact that your tool has problems paring the basic wiki syntax correctly (the links delimtied by [braces] are standard since always and are unbreakable: you cannot break in the middle of the left part which is the target). The wiki was there long before (years) your tool doing incorrect parsing.
We've made a way to parse it correctly with standardized tools, and still you don't want it.
Just remember that what you use is just a helper in order to create your bulletin but this still requires rereading. I've never broken the wiki and even made sure it was using a coherent and clean syntax everywhere.
And your tool is not the only user of the wiki. There's now support for microformats that are perfectly usable too for publishing on other sites where this format is now extremely common on many blogs.

**Comment by TheFive** [comment]
Hi @verdy-p,
Looks like your hCalendar interpreter creates similar problems:
https://glennjones.net/tools/microformats/?url=http%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FCurrent_events&callback=&dateformat=auto



```
"items": [{
        "type": ["h-event"],
        "properties": {
            "category": [""],
            "start": ["2017-10-19"],
            "end": ["2017-10-23"],
            "name": ["State of the Map U.S. 2017, Boulder, Colorado, United States"]
        }
    }, {
        "type": ["h-event"],
        "properties": {
            "category": [""],
            "start": ["2017-10-20"],
            "end": ["2017-10-22"],
            "name": ["Design the Smart Mobility Hackathon, Hamburg, Germany"]
        }
    }, {
```
If you try to intprete the "category of an entry" by comma, it is very hard to handle 4 commata.

The problem is not, that my tool has a bug, the problem is your unflexibility in handling that temporarily. But as i have suggested already: Please support the weeklyOSM team with a calendar (markdown or html).
As i have stated, my time is limited.

**Comment by verdy-p** [comment]
I'd would have loved using a more precise perty in microformat, but because your tool was still continuing to parse the source wikicode (stil lincorerctly) it was impossible to change it more.
without your parser, this calander would have used a template to detail all fields more precisely, including with better geolocation.
For now the calendar has ALWYAS used since the begining an wikitable with three columns, and we have had lot of ficculties to change the format BECAUSE of your existing parser that appeared later and assumed too many false things and was not correctly interpreting the wiki syntax.

So if you want a better microformat with more properties than just "name", I can continue on it, but be ready to adapt your tool when we'll have more properties (hCalendar is still not used as precisely as we could, because I really took are of maintenaing some high compatiblity with your wikicode parser.

But definitely we could have BOTH:
- more precise geotagging
- better handling of icons
- better integration of links
- flexibility for the presentation (not all events will contain a "city", there has always been some nationwide events, or even intenrational events online, with events not geolocated at all)

**Comment by verdy-p** [comment]
Note: the category in your example should never be empty, it is fed bad the first column containing the event type

**Comment by verdy-p** [comment]
Also I don't have any personal microformat interpreter, the doc contains an example of conforming parser found as an example on the hCalendar documentation and reference site.
And there's a link on the doc which already does that parsing: that parser is NOT mine.

**Comment by verdy-p** [comment]
And anyway if you expect to have only two commas on an event description this has never been fixed. There are good reasons why one would need to locate a city within a region before the country, and there may be commas anywhere before. Some events will also not be located precisely in a single city, but a region, or seomtimes several regions or countries simultaneously.
The hCalendar format can support this, but for reading it in the small constrained width of ther table shown on the wiki, the presentation is simplified or there is a need to alter the order.
So even if you use your tool, it can only be a timesaver to help you reformat what you need in your weekly bulletin, but you still need to review what it generates and see how to refit the content.
We won't be able to automate things as long as you use your too limited wiki parser and blindly use what it detects (incorrectly).
We should have been able to use templates since long to make things easier to understand and edit without errors, but it was for now impossible BECAUSE of your existing parser.
I made the initial effort to have it now working correctly with hCalendar readers, we can then progress by using templates and more capabilities. But this requires testing. I've not broken more the existing format when introducing microformats, it should have remained compatible with any basically compliant wikiparser and without complicating too much the addition of events.
I documented everything, with examples for the most common cases. But it was not easy to preserve the compatibility with the rest of the wiki.

**Comment by TheFive** [comment]
Sorry tldr. 

You can develop the microformat interpreter as you want. We can switch off werklyOsM Calendar presentation from now, if you like.

**Comment by fredao** [comment]
@verdy-p 
- long roguish speeches - as always.
- do what you want with YOUR wiki-calendar. weeklyOSM will cancel this service without replacement.
- So you are free to develop for the other users as it is necessary, without discussing changes beforehand.

**Comment by verdy-p** [comment]
Now I"ve been insulted gratuitous lee and personnaly. With additional false statements.
No, I've made things in plain respect of your work and many many times before. I was perfectly concious of your existence, otherwiser the changes would have been more radical, and I've already made many changes to make sure your tool would continue to work.
But it's a fact that insteadf of fixing a small result of your tool where it bugs sometimes, or fixcing the tool, you just paralyze the wiki which was never intended to follow your rules.

NO, there's never been any requirement to use the form "cityname, country" name at end of these events, it was only suggested. As well ther's never been any requirement that this should be in English, or a requirement that links should not be used there, or about which link targets are suitable (internal wikilinks or links to OSM map coordinates or link to OSM object browser, or link to external site). They always have been very liberal. And not all events will require a city name (this has occured many times in the past).

**Comment by TheFive** [comment]
As some of the last comments, including mine, are off topic I close this issue finally. I think the right people will find the right place to discusd the support for the community with calendar data in weeklyOSM, the one and only motivation i have followed with my tools.
