### ISSUE TITLE
Better Integration of (only)reviewer in production flow

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#773]
In ES, EN und FR haben wir muttersprachliche Reviewer, die sich nicht am Schreiben von Nachrichten beteiligen. Diese Reviewer sind auch in MM nicht (oder nur rudimentär) aktiv. Wenn nun ein Blog auf Review gesetzt wird, dann geht eine Meldung an MM. Diese inaktiven Reviewer lesen offensichtlich diese Meldungen nicht. Erst, wenn ich sie persönlich anspreche mit BEISPIEL: @abc @bcd @efg ... 408 ready for review https://osmbc.openstreetmap.de/blog/WN408/Review kommt idR Bewegung in die Reviews.

Edit: typos

**Comment by TheFive** [comment]
Osmbc bieter mAn die Option alle Meldungen die an MM gehen auch per Mail zu versenden. Evtl muss da noch ein wenig trash raus. Sollte aber prinzipiell gehen. Persönliche Snsprach wird OSMBC nie ersetzten können :-(

**Comment by fredao** [comment]
persönliche Ansprache +1
btw es war nicht für URLAUBER! ;-)

**Comment by TheFive** [comment]
Variant A)
The Status Change Option for sending out EMails gets an additional option "Only Review Messages"
This will remove blog is created blog is in edit mode blog is closed from the mails.
So anyone, who puts his email (and validates it) into OSMBC can be informed by only Review messages to his email adress.

Variant B)
All status text becomes configurable (for each language) so that it can be individual configured like
"Der Review der deutschen Wochhennotiz wurde gestartet. (@nakaner @fredao)"
"The review of the weeklyOSM is started. (@dddd @ffff)"

Variant B needs a configuration of "the reviewer" in the OSMBC configuration (which is not so nice style). Variant A needs to ensure, that the reviewer have a working email adress in OSMBC.

Variant C)
Do all the communication staff, done via email, via PM in Mattermost as an alternative.

**Comment by TheFive** [comment]
Isn't this the solution already ?
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/6240370/44300966-aac9f800-a30f-11e8-8597-886f88d6073a.png">

May be i can "rename" the feature and change the EMail text. but in prinzipile this is sending out Review Messages and Blog Closed Information. (Everything a reviewer should know).
