### ISSUE TITLE
warning about flag link is twice in a tranlated version

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#866]
here: https://osmbc.openstreetmap.de/article/24256

you get the warning: 
`Link https://weeklyosm.eu/wp-content/uploads/sites/4/2020/09/es-green.svg is used twice in markdown`

This always happens when the automatic translation logo is used more than once in a translation. 
Maybe it is possible to turn off the warning for the language links?

**Comment by TheFive** [comment]
Would say thats a bug

**Comment by TheFive** [comment]
mm i have seen, the problem is more complex than thought
This is the ES flag link in blue and green

https://blog.openstreetmap.de/wp-uploads/2016/12/es.svg
https://weeklyosm.eu/wp-content/uploads/sites/4/2020/09/es-green.svg

It looks like OSMBC is not aware of the different colors of the language flags so it cant decide, wethere a language flag is correct or incorrect.

I just can switch of every error message for content, that is taken from blog.openstreetmap.de and from weeklyosm.eu.

May be that is a pragmatical solution, which increases the risc in a very seldom error, but as it decreases the error messages it will become more helpfull.

What do you think ?

**Comment by TheFive** [comment]
Question beside: do the flags not disturb the flow in reading ? What is your audience thinking about that ?
