### ISSUE TITLE
Move Re-generate Calendar button to the top

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#990]
Can we please move the button to Re-generate the calender above the article text field. Currently it is below and for long calendars i have to scroll a lot to get to the button.

**Comment by fredao** [comment]
I think the "Regenerate" button is in exactly the right place. 

Reason: The button is only necessary if the entire blog has been translated from EN into the target language and EN is already set to Review. Since this is usually only done by some languages, these languages should then also check their calendar.

**Comment by Strubbl** [comment]
Ok, i'd translated all languages from EN and was regenerating all the translated calendar articles. And it was annoying to always scroll so much over the very long textarea of the article, which has also scrollbars itself.

**Comment by fredao** [comment]
In this case, I can understand your concern.

If the following order is followed (!!before EN is set to Review!!)
1. automatic translation of the entire blog into the target language 
2. set target language to Review (this will create the calendar correctly)

There is no need to regenerate the calendar.
